#!/bin/bash

echo "Uninstall miniserverbackup " >/tmp/uninstallminiserverbackup.log 2>&1 
rm /tmp/backupstate.txt 
echo "Uninstallation done" >>/tmp/uninstallminiserverbackup.log 2>&1 
date >>/tmp/uninstallminiserverbackup.log 2>&1 
exit 0
